import 'package:flutter/foundation.dart';

bool? _parseBool(dynamic value) {
  if (value == null) return null;
  if (value is bool) return value;
  if (value is int) return value == 1;
  if (value is String) {
    String v = value.toLowerCase().trim();
    return v == "true" || v == "1" || v == "yes";
  }
  return false;
}

class FormModel {
  String? uniqueKey;
  String? title;
  String? description;
  String? submissionUrl;
  String? methodType;
  List<FormFileds>? formFileds;
  List<FormFieldGroup>? formGroups;
  List<dynamic>? formElements; // Mixed list to preserve order

  FormModel({
    this.uniqueKey,
    this.title,
    this.description,
    this.submissionUrl,
    this.methodType,
    this.formFileds,
    this.formGroups,
    this.formElements,
  });

  FormModel.fromJson(Map<String, dynamic> json) {
    uniqueKey = json['unique_key']?.toString();
    title = (json['title'] ?? json['form_title'])?.toString();
    description = json['description']?.toString();
    submissionUrl = json['submission_url']?.toString();
    methodType = json['method_type']?.toString();

    var fieldsRaw =
        json['form_fileds'] ?? json['form_fields'] ?? json['fields'];
    if (fieldsRaw != null && fieldsRaw is List) {
      formFileds = <FormFileds>[];
      formGroups = <FormFieldGroup>[];
      formElements = [];
      for (var v in fieldsRaw) {
        if (v is Map<String, dynamic>) {
          if (v.containsKey('group_fields') ||
              (v.containsKey('fields') && v['fields'] is List)) {
            var group = FormFieldGroup.fromJson(v);
            formGroups!.add(group);
            formElements!.add(group);
          } else {
            var field = FormFileds.fromJson(v);
            formFileds!.add(field);
            formElements!.add(field);
          }
        }
      }
    }

    var customFieldsRaw =
        json['custom_fileds'] ?? json['customfields'] ?? json['custom_fields'];
    if (customFieldsRaw != null && customFieldsRaw is List) {
      formFileds ??= <FormFileds>[];
      for (var v in customFieldsRaw) {
        formFileds!.add(FormFileds.fromJson(v));
      }
    }

    var groupsRaw = json['form_groups'] ?? json['groups'];
    if (groupsRaw != null && groupsRaw is List) {
      formGroups ??= <FormFieldGroup>[];
      formElements ??= [];
      for (var v in groupsRaw) {
        var group = FormFieldGroup.fromJson(v);
        formGroups!.add(group);
        formElements!.add(group);
      }
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['unique_key'] = uniqueKey;
    data['title'] = title;
    data['description'] = description;
    data['submission_url'] = submissionUrl;
    data['method_type'] = methodType;
    if (formFileds != null) {
      data['form_fileds'] = formFileds!.map((v) => v.toJson()).toList();
    }
    if (formGroups != null) {
      data['form_groups'] = formGroups!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class FormFieldGroup {
  String? groupTitle;
  List<FormFileds>? fields;

  FormFieldGroup({this.groupTitle, this.fields});

  FormFieldGroup.fromJson(Map<String, dynamic> json) {
    groupTitle =
        (json['group_title'] ?? json['title'] ?? json['label'] ?? json['name'])
            ?.toString();
    var fieldsRaw =
        json['group_fields'] ??
        json['fields'] ??
        json['form_fileds'] ??
        json['form_fields'];
    if (fieldsRaw != null && fieldsRaw is List) {
      fields = <FormFileds>[];
      for (var v in fieldsRaw) {
        fields!.add(FormFileds.fromJson(v));
      }
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['group_title'] = groupTitle;
    if (fields != null) {
      data['fields'] = fields!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class FormFileds {
  String? fieldVisibility;
  String? fieldName;
  String? fieldText;
  String? fieldType;
  bool? fieldRequired;
  bool? fieldAutoGenerated;
  bool? fieldEditable;
  String? fieldDefault;
  dynamic fieldOptions; // Can be List<String> or Map<String, dynamic>

  FormFileds({
    this.fieldVisibility,
    this.fieldName,
    this.fieldText,
    this.fieldType,
    this.fieldRequired,
    this.fieldAutoGenerated,
    this.fieldEditable,
    this.fieldDefault,
    this.fieldOptions,
  });

  FormFileds.fromJson(Map<String, dynamic> json) {
    fieldVisibility =
        (json['field_visibility'] ?? json['visibility'] ?? json['visible'])
            ?.toString();
    fieldName = (json['field_name'] ?? json['name'] ?? json['key'])?.toString();
    fieldText =
        (json['field_text'] ?? json['text'] ?? json['label'] ?? json['title'])
            ?.toString();
    fieldType = (json['field_type'] ?? json['type'] ?? json['fieldtype'])
        ?.toString();

    fieldRequired = _parseBool(
      json['field_required'] ?? json['required'] ?? json['is_required'],
    );
    fieldAutoGenerated = _parseBool(
      json['field_auto_generated'] ?? json['auto_generated'] ?? json['is_auto'],
    );

    // Check for editable key, then fall back to reversed readonly/disabled
    bool? editable = _parseBool(
      json['field_editable'] ??
          json['editable'] ??
          json['is_editable'] ??
          json['enabled'],
    );
    bool? readonly = _parseBool(
      json['readonly'] ?? json['read_only'] ?? json['is_readonly'],
    );
    bool? disabled = _parseBool(json['disabled'] ?? json['is_disabled']);

    if (editable != null) {
      fieldEditable = editable;
    } else if (readonly != null) {
      fieldEditable = !readonly;
    } else if (disabled != null) {
      fieldEditable = !disabled;
    } else {
      fieldEditable = null; // Default will be handled in UI
    }

    fieldDefault =
        (json['field_default'] ??
                json['default_value'] ??
                json['default'] ??
                json['value'])
            ?.toString();

    var optionsRaw =
        json['field_options'] ?? json['options'] ?? json['choices'];
    if (optionsRaw != null) {
      if (optionsRaw is Map) {
        fieldOptions = Map<String, dynamic>.from(optionsRaw);
      } else if (optionsRaw is List) {
        fieldOptions = List<String>.from(optionsRaw.map((e) => e.toString()));
      } else if (optionsRaw is String && optionsRaw.contains(',')) {
        fieldOptions = optionsRaw.split(',').map((e) => e.trim()).toList();
      }
    }

    if (fieldOptions != null) {
      debugPrint("Parsed Options for $fieldName: $fieldOptions");
    }

    debugPrint(
      "Parsed Field: $fieldName, Type: $fieldType, Editable: $fieldEditable (Raw: ${json['field_editable'] ?? json['editable']})",
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['field_visibility'] = fieldVisibility;
    data['field_name'] = fieldName;
    data['field_text'] = fieldText;
    data['field_type'] = fieldType;
    data['field_required'] = fieldRequired;
    data['field_auto_generated'] = fieldAutoGenerated;
    data['field_editable'] = fieldEditable;
    data['field_default'] = fieldDefault;
    if (fieldOptions != null) {
      data['field_options'] = fieldOptions;
    }
    return data;
  }
}
